### ISSUE TITLE
Implement C API

### ISSUE THREAD

**Issue by Ygg01** [Ygg01/xml5ever#2]
Implement basic C API similar to [tendril's](https://github.com/servo/tendril) C API[1]. 

Additional sub task may include:
* Also test C API to verify it works and behaves similarly.
* Assure that C API has similar performances.

[1]https://github.com/servo/tendril/tree/master/capi/

**Comment by SimonSapin** [comment]
Note that currently html5ever’s C API only has the tokenizer, but that’s the least interesting part IMO. Outside of tests, users probably only care about the tokenizer and tree builder together, as a whole. Also, it’s possible that it doesn’t work right now: https://github.com/servo/html5ever/issues/143

**Comment by Ygg01** [comment]
I meant more as in way code is organized, i.e. separate into a crate, test using cargo test, etc.

**Comment by SimonSapin** [comment]
Well, html5ever’s C API doesn’t have tests yet. Tendril’s does, though: https://github.com/servo/tendril/tree/master/capi/ctest

**Comment by Ygg01** [comment]
I think this should be in a separate crate/project and not an independent API. 

Closing.
