### ISSUE TITLE
Move into the html5ever repository?

### ISSUE THREAD

**Issue by SimonSapin** [Ygg01/xml5ever#30]
I was the one reluctant to do this when this project started, but now that Servo uses both x5e and h5e semi-interchangeably it turns out that having them in the same repo would make our lives easier when doing things like refactoring the input handling to deal with `</script>` or character encodings.

@Ygg01 how do you feel about this?

CC @nox

**Comment by nox** [comment]
I would like to see a `markup5ever` crate with `BufferQueue` and other shared things, and h5e and x5e on top of it.

**Comment by SimonSapin** [comment]
In the other things: TreeSink?, rcdom, smallcharset, …

There’s already `html5ever_atoms` which is only a separate crate in order to be also used in x5e, it could be renamed/repurposed into markup5ever.

Or maybe everything in a single crate?

**Comment by Ygg01** [comment]
@SimonSapin Hm. I feel good about this change. I tried to make it easy for Servo folks to change it as needed, since I was less active than I wanted. 

You could fork the current repository into servo/xml5ever and I could delete this repo, correct?

**Comment by SimonSapin** [comment]
No need to transfer any repository, I think. The plan, if you’re happy with it, is:

* To preserve git history I’ll start from a clone of this repository, move everything into a new `xml5ever` subdirectory, and merge that branch into https://github.com/servo/html5ever
* I’ll change the `repository` and `homepage` entries in `Cargo.toml` to https://github.com/servo/html5ever
* I’ll push to this repo a new `moved` branch with just a README that says that xml5ever is now at https://github.com/servo/html5ever/tree/master/xml5ever
* I’ll publish a new version to crates.io with this updated metadata
* I’ll ask you (since I don’t have admin access to do it myself) to go into this repository’s settings and change the default branch to `move`, so that’s people what people see when they go to https://github.com/Ygg01/xml5ever . We’ll keep the `master` branch around in case someone still wants to look it it.

I think that’s all we need to complete the move. After that, @nox or I will work on refactoring, sharing more code, etc.

I don’t expect we’ll need to make many changes to `xml5lib-test`, so we can make pull requests when that happens. (And temporarily mark some tests as expected failures in the meantime if we need to.) Similarly for `xml5draft`.

**Comment by Ygg01** [comment]
Sounds good. Will you need any other help?

**Comment by SimonSapin** [comment]
@Ygg01 I think we’re good. The html5ever pull request is at https://github.com/servo/html5ever/pull/254, an the README-only branch at: https://github.com/Ygg01/xml5ever/tree/moved. The latter has a broken link which will start being valid once the former is merged.

Can you make the default branch change? https://help.github.com/articles/setting-the-default-branch/

**Comment by Ygg01** [comment]
Done and done.
