### ISSUE TITLE
Add Namespaces into xml5ever

### ISSUE THREAD

**Issue by Ygg01** [Ygg01/xml5ever#7]
Namespaces are kinda required for having a solid XML parser, so we should add it. However. It might require reworking a large portion of our existing code base which relies on `string_cache`. Other option is for `string_cache` to allow custom namespaces.

For further reading see:
https://github.com/servo/string-cache/issues/29
http://www.w3.org/TR/REC-xml-names/
http://www.xmlmaster.org/en/article/d01/c10/

**Comment by SimonSapin** [comment]
> Other option is for `string_cache` to allow custom namespaces.

Does it not already? `Namespace(Atom::from_slice("..."))` can be used with any string (URL in this case), it’s only the `ns!` macro (like the `atom!` macro) that only works with a set of strings known at compile time.

**Comment by SimonSapin** [comment]
See also http://doc.servo.org/string_cache/namespace/struct.QualName.html

**Comment by Ygg01** [comment]
@SimonSapin From issues, servo/string-cache#26 and servo/string-cache#29 I gathered there was some functionality missing from string_cache that XML needs. I was going to dig deeper into it, but string_cache lacks docs and namespaces are not too high on priority list.

**Comment by Ygg01** [comment]
@SimonSapin After digging a bit, I think I have a gist of it. I want to store a triple of following information: prefix, local-name and namespace (e.g. `html:body` prefix is `html`, local name is 'body' and namespace is `http://www.w3.org/1999/xhtml`).

However, qualified name has two fields. So two ideas spring to mind:

1. Lose prefix and store local into QualName
1. Story full name into QualName local

My favorite option is the first one, but will other libraries like `kuchiki` need that information? Second solution preserves information, but potentially makes extracting local name more painful :question:

**Comment by SimonSapin** [comment]
It’s not clear to me whether Kuchiki needs to preserve prefixes:

It sounds like you want either:

```rust
struct Name {
    prefix: Atom,
    qual_name: string_cache::QualName,
}
```
or
```rust
struct QualName {
    prefix: Atom,
    local_name: Atom,
    namespace_url: Atom,
}
```

The former seems less convenient to use.

https://github.com/servo/string-cache/issues/26 is about changing `string_cache::QualName` to be the latter, but you can also define it yourself. No need to wait for us (the Servo team) to agree between ourselves and do it.

**Comment by Ygg01** [comment]
I think this is more or less finished, barring some kind of bug fixing.
